name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      # ✅ Docker Login
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ✅ Build Image
      - name: Build Docker Image
        run: |
          docker build \
            --build-arg TMDB_V3_API_KEY=${{ secrets.TMDB_API_KEY }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/netflix:${{ github.sha }} .

      # ✅ Trivy Scan
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/netflix:${{ github.sha }}
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

      # ✅ Push Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/netflix:${{ github.sha }}

      # ✅ Update Helm Values
      - name: Update Helm Image Tag
        run: |
          sed -i "s/tag:.*/tag: ${{ github.sha }}/" netflix-chart/values.yaml

      # ✅ Commit Updated Values
      - name: Commit Helm Update
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add netflix-chart/values.yaml
          git commit -m "Update image tag"
          git push
